### ISSUE TITLE
Trying to run all unit tests from a source folder also runs the instrumented tests

### ISSUE THREAD

**Issue by Mugurell** [mannodermaus/android-junit5#142] opened 2019-01-30 08:09 UTC
Tried also on the provided sample.
Video - https://drive.google.com/file/d/1iu-Yr7H5cPzzN3TTsFWJZX1m2byXFHKL/view?usp=sharing

Although not clearly seen in the above video this behavior clearly skews the expected results but furthermore, when instrumented tests would try to access Android apis they would fail.

**Comment by mannodermaus** [comment] 2019-02-03 08:16
I can kind of confirm this after experimenting around with it. Seems like the IDE-based Run Configurations share the classpath for both test types to some extent, and only if you run the instrumentation tests first, will the unit tests include them as well.

**Unit Tests**
<img width="742" alt="screen shot 2019-02-03 at 16 59 35" src="https://user-images.githubusercontent.com/3897705/52174307-37d90e80-27d5-11e9-9f4c-c95a6c7fb14c.png">

**Instrumentation Tests**
<img width="742" alt="screen shot 2019-02-03 at 16 59 19" src="https://user-images.githubusercontent.com/3897705/52174313-432c3a00-27d5-11e9-8fb5-a4b600e037d0.png">

**Output of "Unit Tests" when executed first**
<img width="546" alt="screen shot 2019-02-03 at 17 05 10" src="https://user-images.githubusercontent.com/3897705/52174389-44119b80-27d6-11e9-9f5c-ae8a98d0b0e9.png">

**Output of "Unit Tests" when executed last**
<img width="540" alt="screen shot 2019-02-03 at 17 08 51" src="https://user-images.githubusercontent.com/3897705/52174400-67d4e180-27d6-11e9-8ae7-7293a82ea198.png">

Running a Gradle `clean` seems to disconnect the two again - if you include that as a step in the "Before Launch" section of the unit test Run Configuration (before "Gradle-aware Make"), it works as well. Of course, that's not a very feasible solution, though.

<img width="451" alt="screen shot 2019-02-03 at 17 16 21" src="https://user-images.githubusercontent.com/3897705/52174473-7cfe4000-27d7-11e9-865f-60d97f72748a.png">

The plugin doesn't really have a say in how the IDE's Run Configurations handle the classpath, and as far as I'm aware, there is really little control over this. I'll review what weird caching might be going on in the background, but it might also just be an IDE bug.

**Comment by mannodermaus** [comment] 2021-07-31 19:31
In the latest versions of Android Studio, the option to right-click a package inside `androidTest` seems to be removed. I'm unable to reproduce the mixing of executed tests with the Bumblebee canary build and AS 4.2.2. I'm considering this problem fixed by AS and will close down here.

**Closed by mannodermaus** 2021-07-31 19:31 UTC
Labels: possibly-as-bug
