### ISSUE TITLE
Rework kotlin class detection in AGP3

### ISSUE THREAD

**Issue by raniejade** [mannodermaus/android-junit5#29] opened 2017-11-10 04:26 UTC
Add the kotlin output directory to the classpath Instead of copying kotlin classes to `intermediates` folder. Was able to do it in Spek's AS plugin by using an API provided by AS3 (see https://github.com/raniejade/spek-idea-plugin/blob/master/plugin-studio3.0/src/main/kotlin/org/jetbrains/spek/studio/SpekAndroidParameterPatcher.kt). Probably the same API is available in AGP3. Some users are reporting issues caused by the copy during dexing, removing the copy tasks fixes the issue.

**Comment by mannodermaus** [comment] 2017-11-11 11:31
I'm hesitant towards the idea to extend the scope of this plugin to IDE-specific patches, since I'm assuming that a similar workaround would have to be made for IDEA and Studio 2.x versions as well (judging from the linked source).

Could you link some of the issues caused by copying Kotlin output to `intermediates`? Thanks!

**Comment by raniejade** [comment] 2017-11-11 13:21
Here's one: https://github.com/spekframework/spek/issues/256#issuecomment-343136918. I don't think it's an IDE-specific patch, the `JavaArtifact#additionalSourcesDir` is probably used somehow in AGP3.

**Comment by mannodermaus** [comment] 2017-11-11 13:39
Thanks! I'll investigate a little.

**Comment by mannodermaus** [comment] 2017-11-15 13:00
Another point of concern in applying a patch like this inside the JUnit 5 plugin is the requirement to depend on a local installation of Android Studio. This would be a problem when it comes to our Travis CI builds, since we wouldn't have access to a `$localAndroidStudio` there.

**Comment by raniejade** [comment] 2017-11-15 13:39
Do you really need the full installation? Is there a way to just pull in AGP3 dependencies?

**Comment by mannodermaus** [comment] 2017-11-19 15:24
I was just going off the way you reach into the IDE's plugin dependencies to obtain the `compileOnly` code necessary to provide Spek support. Pretty cool actually! There are some internal APIs inside AGP3 which could theoretically allow somebody to register additional artifacts (by means of `ExtraModelInfo`), however I'd rather not touch those internals.

Meanwhile, it seems that the Kotlin integration into the IDE has been improved quite a bit in the most recent releases, so that they are detected properly even from the `/tmp` folders. Also, when working on Kotlin translation earlier, I stumbled upon an interesting fact about the legacy integration between Java and Kotlin. In fact, on projects using AGP2, the Kotlin plugin automatically performs the Copy task itself! This might also have been a cause for accidental duplication of classes. The next version of `android-junit5` won't perform any copying on its own anymore, and instead collect its inputs from a new `TestRootDirectoryProvider` interface, which is contributed to from the Kotlin compilation tasks directly.

**Comment by mannodermaus** [comment] 2017-11-20 12:49
Released in `1.0.20`.

**Closed by mannodermaus** 2017-11-20 12:49 UTC
Labels: question
