### ISSUE TITLE
Test filtering doesn't work on the latest SNAPSHOT

### ISSUE THREAD

**Issue by olga999999** [mannodermaus/android-junit5#339] opened 2024-06-10 02:51 UTC
Execution of the individual test cases from command line and AS doesn't work on the latest 1.5.0-SNAPSHOT. No tests are being executed at all.
It worked fine before, so most likely it is caused by #335 or #336. 
Sample command:
`./gradlew  -Pandroid.testInstrumentationRunnerArguments.class=com.example.ExampleTest1#parametrizedTest :app:cAT`

**Comment by mannodermaus** [comment] 2024-06-14 10:37
Hey, thanks for reporting. I can confirm that this is indeed happening because of the change in #335, and it's no wonder it fails for a test class with test cases foreign to the JUnit 4-based Android instrumentation. Not sure yet how I want to tackle this, since there are a lot of benefits to relying on the counting performed by Android, but we definitely need to take dynamic tests into account here.

**Comment by mannodermaus** [comment] 2024-06-15 06:55
This is merged into the snapshot and should be ready in about 15 minutes. Let me know if it resolves your issue!

**Closed** 2024-06-15 06:55 UTC
Labels: bug

**Comment by mannodermaus** [comment] 2024-06-15 14:08
I did and it did, yeah. The mechanism for any non-@Test method is the same, so it shouldn't matter which one is used. Could be that your snapshot isn't refreshed to the latest variant from earlier today or something? Let me give this one more spin.

**Comment by mannodermaus** [comment] 2024-06-15 15:56
Sorry about that. Turns out Maven Central migrated off of the old authentication mechanism for publishing artifacts, and triggered the switch for this repository somewhere in the last few days. I was able to update and re-deploy, please try again.
