### ISSUE TITLE
TestEngine with ID 'junit-jupiter' failed to discover tests

### ISSUE THREAD

**Issue by Doums** [mannodermaus/android-junit5#51] opened 2018-02-01 18:57 UTC
Hi,

I try to implement instrumented unit tests.
I work with Android Studio 3.0.1

My top Level build.gradle:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.2.21'

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath "de.mannodermaus.gradle.plugins:android-junit5:1.0.30"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
My app-level build.gradle:
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: "de.mannodermaus.android-junit5"

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.todo.app"
        minSdkVersion 26
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    testOptions {
        // Configuration closure added by the plugin;
        // all configurable parameters related to JUnit 5 can be found here
        junitPlatform {
            // The JUnit Jupiter dependency version to use
            jupiterVersion "5.0.3"

            // The JUnit Vintage Engine dependency version to use
            vintageVersion "4.12.2"

            // Options related to running unit tests with JUnit 5.
            unitTests {
                // Whether or not JUnit 5 test tasks should be affected by
                // JVM Arguments, System Properties & Environment Variables
                // declared through "unitTests.all" closures
                applyDefaultTestOptions true
            }

            // Options related to running instrumented tests with JUnit 5.
            // This is an incubating feature which utilizes the backwards-compatibility
            // of the JUnit Platform in order to enhance the default Test Instrumentation Runner
            // with new power. However, because of their experimental nature and steep minSdkVersion requirement,
            // they are turned off by default. If you choose to enable them, you also have to declare
            // the library dependency in your androidTest scope. Please refer to the "Setup"
            // section for more details.
            instrumentationTests {
                enabled true

                // The Android-Instrumentation-Test dependency version to use
                version "0.1.1"
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.android.support:cardview-v7:26.1.0'
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testCompile 'org.junit.jupiter:junit-jupiter-api:5.0.3'
    testCompile "org.mockito:mockito-core:2.13.0"

    // (Required) Writing and executing Unit Tests on the JUnit Platform.
    testImplementation junit5.unitTests()

    // (Optional) If you need "Parameterized Tests".
    testImplementation junit5.parameterized()

    // (Optional) For running tests inside Android Studio 3.x
    testCompileOnly junit5.unitTestsRuntime()

    androidTestImplementation junit5.instrumentationTests()
}

repositories {
    mavenCentral()
}

apply plugin: 'kotlin-android-extensions'
```

Under src/androidTest/java/com.myapp.app/ExempleInstrumentedTest my test:
```
package com.todo.app

import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

class ExampleInstrumentedTest {

    @Test
    fun test() {

        // Read the data.
        assertEquals(true, true, "test")
    }
}
```

When I try to launch this test I got this error (on android studio):
```
févr. 01, 2018 7:48:50 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
AVERTISSEMENT: TestEngine with ID 'junit-jupiter' failed to discover tests
org.junit.platform.commons.util.PreconditionViolationException: Could not load class with name: com.todo.app.ExampleInstrumentedTest
```
and

```
févr. 01, 2018 7:48:50 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
AVERTISSEMENT: TestEngine with ID 'junit-vintage' failed to discover tests
org.junit.platform.commons.util.PreconditionViolationException: Could not load class with name: com.todo.app.ExampleInstrumentedTest
```

```
Process finished with exit code 0
Empty test suite.
```

What is the problem ?

**Comment by mannodermaus** [comment] 2018-02-02 00:46
For instrumented tests, can you check and share the output in Logcat around the time when the test is being executed? Usually, that can yield more info about what is failing your execution.

**Comment by mannodermaus** [comment] 2018-02-15 12:16
Feel free to re-open with more information, I'm closing this for now.

**Closed by mannodermaus** 2018-02-15 12:16 UTC
Labels: question

**Comment by vasticles** [comment] 2018-03-23 17:43
Not sure if you get notified about a reply to a closed issue, so... @mannodermaus (sorry)

**Comment by mannodermaus** [comment] 2018-03-24 05:29
Can you share your `build.gradle`config for the plugin? Specifically, I'd like to know what versions of the plugin / the instrumentation library you're pulling in. There has been quite a lot of development recently, and I'm wondering if upgrading to the latest and greatest will already do the trick for you.

**Comment by vasticles** [comment] 2018-03-25 14:47
Here they are:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.2.30'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "de.mannodermaus.gradle.plugins:android-junit5:1.0.31"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```


...and...

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'de.mannodermaus.android-junit5'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.todo.app"
        minSdkVersion 26
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    testOptions {
        junitPlatform {
            jupiterVersion "5.0.3"
            vintageVersion "4.12.2"

            unitTests {
                applyDefaultTestOptions true
            }

            instrumentationTests {
                enabled true
                version "0.1.1"
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    testImplementation 'junit:junit:4.12'
    testImplementation junit5.unitTests()
    testImplementation junit5.parameterized()
    testCompileOnly junit5.unitTestsRuntime()
    androidTestImplementation junit5.instrumentationTests()
    testImplementation 'org.assertj:assertj-core:3.8.0'
}
```

**Comment by mannodermaus** [comment] 2018-03-26 02:49
Can you remove your `instrumentationTests.version` declaration? By default it will always use the latest available version, which is `0.2.1` right now. Lots of bugfixes from the version you're pulling in, so let me know if the problem persists after upgrading that library!

**Comment by vasticles** [comment] 2018-03-26 07:35
No luck. Same error :(

**Comment by mannodermaus** [comment] 2018-03-26 08:44
Can you verify that `com.todo.app.ExampleInstrumentedTest.class` exists in the build folder? Also, not sure if this is necessary or related, but I noticed that you don't declare the `com.android.support.test:runner` dependency in your build.gradle, yet reference the `AndroidJUnitRunner` correctly - the instrumentation test library for JUnit 5 hooks into the support test library using specific APIs in `AndroidJUnitRunner`. Lastly, check if declaring Java 8 as both the compile and target language versions will do anything to improve the situation.

**Comment by vasticles** [comment] 2018-03-26 09:10
I did not see `com.todo.app.ExampleInstrumentedTest.class` in the build folder before the changes, and sadly not after the changes you suggested. Here is a screenshot of the build/tmp folder contents. Please tell me if I'm looking in the wrong place.
<img width="468" alt="screen shot 2018-03-26 at 3 54 12 pm" src="https://user-images.githubusercontent.com/5666413/37897199-d8432b3e-310f-11e8-96f3-11c59f12c4fa.png">

Updated gradle files to reflect your suggestions:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.2.30'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "de.mannodermaus.gradle.plugins:android-junit5:1.0.31"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
```

and

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'de.mannodermaus.android-junit5'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.todo.app"
        minSdkVersion 26
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    testOptions {
        junitPlatform {
            jupiterVersion "5.0.3"
            vintageVersion "4.12.2"

            unitTests {
                applyDefaultTestOptions true
            }

            instrumentationTests {
                enabled true
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"

    testImplementation 'junit:junit:4.12'
    testImplementation junit5.unitTests()
    testImplementation junit5.parameterized()
    testCompileOnly junit5.unitTestsRuntime()
    androidTestImplementation junit5.instrumentationTests()
    testImplementation 'org.assertj:assertj-core:3.8.0'

    androidTestImplementation 'com.android.support.test:runner:1.0.1'
}
```

**Comment by mannodermaus** [comment] 2018-03-26 12:07
Compiled Kotlin androidTest classes are found in `build/tmp/kotlin-classes/<debug>AndroidTest`. Try assembling the Android instrumentation tests explicitly with `./gradlew assembleAndroidTest`. In general, kotlinc not compiling Kotlin files is outside of the scope of this plugin, and I can't reproduce this on the sample project:

<img width="342" alt="screen shot 2018-03-26 at 21 06 53" src="https://user-images.githubusercontent.com/3897705/37905382-ab558016-3139-11e8-9af2-54ce3bbe35ec.png">
(Note that the sample project defines JUnit 5 integration in a product flavor, which explains the `Experimental` part of the folder names.)

**Comment by vasticles** [comment] 2018-03-27 09:55
Strange. That compiled without issues from the console. However, I still could not run the tests due to the same error.

**Comment by EbenezerGH** [comment] 2018-08-21 21:11
@vasticles Where are you at now with this issue, i'm having the same problem

**Comment by vasticles** [comment] 2018-08-22 02:09
@EbenezerGH I ended up giving up and going back to JUnit4 for instrumented tests

**Comment by EbenezerGH** [comment] 2018-08-22 02:33
@vasticles I did the same

**Comment by progonkpa** [comment] 2019-03-23 09:44
As you may now Android Studio is basically the same IDE as IntelliJ.
I ran into this issue with IntelliJ Community Edition. I had the newest version of JUnit in my dependencies (5.4.1) which turned out to be an issue.

The error went away after switching to JUnit 5.3.2. I discoverd this version number by removing the JUnit dependencies and letting IntelliJ resolve the import statements.

**Comment by BlackCritical** [comment] 2021-02-19 10:10
I got the same problem using Spring Boot with the Gradle Spring Dependency Management plugin.
This solved my issue without downgrading the Version to 5.3.2:
https://stackoverflow.com/questions/54598484/gradle-5-junit-bom-and-spring-boot-incorrect-versions/54605523#54605523
