### ISSUE TITLE
Running all units tests in folder fails while running all instrumented unit tests works in Android Studio

### ISSUE THREAD

**Issue by ajgay** [mannodermaus/android-junit5#145] opened 2019-02-07 17:28 UTC
![error](https://user-images.githubusercontent.com/6867833/52430296-c4d0e000-2ad3-11e9-86ab-90fa6e7e181e.png)

Running each test individually works fine. I've duplicated this over multiple projects.

**Comment by mannodermaus** [comment] 2019-02-09 11:26
Could you share the following info? At first glance, this looks more like an incompatibility between IDE and JUnit 5, rather than something with the plugin.
- Android Studio version
- Run Configuration used to execute "all unit tests in folder" (with a screenshot)
- Version of the `android-junit5` plugin
- Plugin configuration (using the `android.testOptions` DSL), if any

**Comment by ajgay** [comment] 2019-02-12 18:30
- Studio 3.4 Beta 2 & 3
- android-junit5:1.3.1.1
- No test options

![runconfig](https://user-images.githubusercontent.com/6867833/52659004-69836100-2eca-11e9-8122-70359897f5f7.png)

**Comment by mannodermaus** [comment] 2019-03-03 08:50
Thanks for your patience. I'm able to reproduce this now. Here are my test results:

## Common Setup
- Gradle 5.2
- android-junit5 Plugin 1.4.0.0
- Kotlin 1.3.10

## Scenario 1 (✅)
- Android Studio 3.3.1 (#AI-182.5107)
- Android Gradle Plugin 3.3.1

#### Result
Tests are discovered and executed successfully.

## Scenario 2 (❌)
- Android Studio 3.4 Beta 5 (#AI-183.5429)
- Android Gradle Plugin 3.3.1

#### Result
```
Internal Error occurred.
java.util.NoSuchElementException
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:894)
	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1043)
	at com.intellij.junit5.JUnit5TestRunnerUtil.createSelector(JUnit5TestRunnerUtil.java:181)
	at com.intellij.junit5.JUnit5TestRunnerUtil.buildRequest(JUnit5TestRunnerUtil.java:70)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

## Scenario 3 (❌)
- Android Studio 3.4 Beta 5 (#AI-183.5429)
- Android Gradle Plugin 3.4.0-beta05

#### Result
```
Internal Error occurred.
java.util.NoSuchElementException
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:894)
	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1043)
	at com.intellij.junit5.JUnit5TestRunnerUtil.createSelector(JUnit5TestRunnerUtil.java:181)
	at com.intellij.junit5.JUnit5TestRunnerUtil.buildRequest(JUnit5TestRunnerUtil.java:70)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

## Scenario 4 (❌)
- IntelliJ IDEA Ultimate 2018.3.4 (#IU-183.5429)
- Android Gradle Plugin 3.4.0-beta05

#### Result
Tests are not executed, but `Process finished with exit code 0`.

---

The offending method is located within IntelliJ IDEA, `JUnit5TestRunnerUtil#createSelector`:
- AS 3.3.1 is built on top of IDEA Build *182.5107, which is [this version of the method](https://github.com/JetBrains/intellij-community/blob/182.5107/plugins/junit5_rt/src/com/intellij/junit5/JUnit5TestRunnerUtil.java#L120-L131)
- AS 3.4 is built on top of IDEA Build *183.5429, which is [this version of the method](https://github.com/JetBrains/intellij-community/blob/183.5429/plugins/junit5_rt/src/com/intellij/junit5/JUnit5TestRunnerUtil.java#L174-L189)

The error arises because of the following line. The iterator is unexpectedly empty, which throws the exception:

```java
return DiscoverySelectors.selectClasspathRoots(Collections.singleton(Paths.get(directory))).iterator().next();
```

I'm going to validate the classpath setup of the plugin, because apparently it cannot find any root directory. FWIW, the `UnitTest` Gradle tasks still execute fine, so that would be a workaround for now.

**Comment by mannodermaus** [comment] 2019-03-22 21:50
I was deep-diving into how the IDEs actually work under the hood, starting the test execution. I found that Android Studio 3.4 provides a non-existent directory to the test launcher, namely the `build/intermediates/compile_only_not_namespaced_r_class_jar/debug/generateDebugRFile/R.jar!` path. While this file does exist, the URL points into `R.jar` and doesn't pass `Files::exists`. This creates an empty `Set` in JUnit5's [DiscoverySelectors::selectClasspathRoots](https://github.com/junit-team/junit5/blob/master/junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/DiscoverySelectors.java#L202-L213), which then creates an empty `Iterator` in IntelliJ's [JUnit5TestRunnerUtil::createSelector](https://github.com/JetBrains/intellij-community/blob/master/plugins/junit5_rt/src/com/intellij/junit5/JUnit5TestRunnerUtil.java#L202). Of course, calling `next()` on that empty iterator will fail.

I evaluated IntelliJ to be the best point to apply the change, so I filed [IDEA-209506](https://youtrack.jetbrains.com/issue/IDEA-209506) for this. I'm closing this ticket, since android-junit5 doesn't participate in the creation of the test run by the IDE.

**Closed by mannodermaus** 2019-03-22 21:50 UTC
Labels: bug

**Comment by molokoka** [comment] 2019-04-19 09:33
With release of stable 3.4 in our project we see the same issue :|

**Comment by Denis10** [comment] 2019-07-17 12:06
Android studio 3.4.2 also

**Comment by mannodermaus** [comment] 2019-07-18 06:22
[My proposed fix](https://youtrack.jetbrains.com/issue/IDEA-209506) for this bug in IntelliJ [was already merged upstream](https://github.com/JetBrains/intellij-community/pull/1152), but its release is still pending. Only after that are we going to have a chance of getting this into Android Studio, unfortunately. 🤞
